name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: login to docker hub
        run: echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB}} --password-stdin
      - name: Build docker image
        run: docker build -t casse/backendUsuarios .
      - name: Publish image to docker hub
        run: docker push casse/backendUsuarios:latest


  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Delete old container
        run: sudo docker rm -f api-container
      - name: Delete old image
        run: sudo docker rmi -f casse/backendUsuarios
      - name: Pull image from docker hub
        run: sudo docker pull casse/backendUsuarios:latest
      - name: Run docker container
        run: sudo docker run -d -p 9000:8080 --name api-container --network mi_red --env-file ~/.env casse/backendUsuarios:latest
